version: "3.9"

services:
  db:
    image: postgres
    expose:
      - "5444"
    ports:
      - 5444:5432
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
  web:
    image: sansanchezzz/movie-quotes:latest
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - 8001:8000
    command: gunicorn --bind 0.0.0.0:8000 config.wsgi
#    volumes:
#      - .:/code
    links:
      - db
    depends_on:
      - db
